### ISSUE TITLE
mainwindow never actually is disposed

### ISSUE THREAD

**Issue by nukeandbeans** [Memorix101/SharpQuake#4]
This causes the Quake process to continue running in the background. Adding `mainwindow.Instance.Dispose();` below `mainwindow.Instance.Exit();` at line 232 of `sys.cs` fixes this issue.

I was going to create a PR for this but I'm using a different project setup and didn't want to pollute things.

**Comment by Memorix101** [comment]
Thank you. I will add it. 🙂
